const BASE = process.env.BASE || 'http://127.0.0.1:8765', OUT = process.env.OUT || require('os').tmpdir();
const { chromium } = require('playwright');
const HS = process.env.CHROME_PATH || undefined;
let vq = null;
(async () => {
  const b = await chromium.launch({...(HS ? {executablePath:HS} : {}), args:['--use-gl=swiftshader']});
  const ctx = await b.newContext({viewport:{width:390, height:844}, deviceScaleFactor:2, isMobile:true, hasTouch:true, serviceWorkers:'block', geolocation:{latitude:49.90, longitude:10.00, accuracy:10}, permissions:['geolocation']});
  await ctx.route(/amazonaws|overpass|gstatic|firestore|osrm|photon|open-meteo|nominatim|dwd|rainviewer|arcgis/, r => r.abort());
  await ctx.route(/valhalla/, r => { const q = JSON.parse(new URL(r.request().url()).searchParams.get('json')); vq = q;
    const L = q.locations, co = []; L.forEach((p, i) => { if(i) for(let f = .25; f < 1; f += .25) co.push([L[i-1].lon + (p.lon - L[i-1].lon) * f, L[i-1].lat + (p.lat - L[i-1].lat) * f]); co.push([p.lon, p.lat]); });
    const breaks = L.filter((p, i) => i === 0 || i === L.length - 1 || p.type !== 'through').length;
    const legs = Array.from({length:breaks - 1}, () => ({steps:[{maneuver:{type:'depart'}, name:'Landstraße', distance:5000, duration:300}, {maneuver:{type:'arrive'}, name:'', distance:0, duration:0}]}));
    r.fulfill({status:200, contentType:'application/json', body:JSON.stringify({routes:[{geometry:{type:'LineString', coordinates:co}, legs, duration:1800, distance:breaks * 5000}]})}); });
  await ctx.addInitScript(() => { if(localStorage.getItem('__i')) return; localStorage.setItem('__i', 1);
    localStorage.setItem('meine-spots-prefs', JSON.stringify({labels:true, theme:'dark', onb:1}));
    const mk = (id, name, a, b, n) => { const seg = []; for(let i = 0; i <= n; i++){ const f = i / n; seg.push([+(a[0] + (b[0] - a[0]) * f + Math.sin(f * 9) * .01).toFixed(6), +(a[1] + (b[1] - a[1]) * f).toFixed(6), i * 10]); } return {id, name, created:Date.now() - n * 1e5, dist:20000, dur:1200000, maxSpd:25, segs:[seg]}; };
    localStorage.setItem('meine-spots-tracks', JSON.stringify([mk('a', 'Abendrunde', [10.05, 49.98], [10.3, 49.85], 200), mk('b', 'Zur Arbeit', [10.1, 49.95], [10.2, 50.03], 120), mk('c', 'Bergstrecke', [9.9, 49.8], [9.6, 49.7], 160)])); });
  const page = await ctx.newPage(); const errs = []; page.on('pageerror', e => errs.push(e.message));
  const click = s => page.evaluate(s => { const el = document.querySelector(s); if(!el) throw new Error('missing ' + s); el.click(); }, s);
  const txt = s => page.evaluate(s => (document.querySelector(s) || {}).innerText || null, s);
  const shot = n => page.screenshot({path:`${OUT}/fav-${n}.png`});
  await page.goto(`${BASE}/index.html?noonb`); await page.waitForTimeout(2000);
  await click('[data-tab=tracks]'); await page.waitForTimeout(400);
  console.log('chips before:', await page.evaluate(() => !!document.querySelector('[data-trkfav]')));
  await click('[data-track=c]'); await page.waitForTimeout(600); await shot('1-view');
  await click('[data-tv=fav]'); await page.waitForTimeout(300);
  console.log('fav on:', await page.evaluate(() => document.querySelector('[data-tv=fav]').classList.contains('on')), '| toast:', await txt('#toast'));
  await shot('2-view-fav');
  await click('[data-tv=back]'); await page.waitForTimeout(500);
  console.log('list:', (await txt('#listBody')).replace(/\n+/g, ' / ').slice(0, 200)); await shot('3-list');
  await click('[data-trkfav="1"]'); await page.waitForTimeout(300);
  console.log('filtered items:', await page.evaluate(() => [...document.querySelectorAll('#listBody [data-track]')].map(x => x.dataset.track).join()));
  await shot('4-filtered');
  await click('[data-track=c]'); await page.waitForTimeout(500);
  await click('[data-tv=again]'); await page.waitForTimeout(2500);
  console.log('valhalla locs:', vq && vq.locations.length, vq && vq.locations.map(l => l.type || 'break').join(','), 'hw:', vq && vq.costing_options.auto.use_highways);
  console.log('navPrev:', (await txt('#navPrev') || '').replace(/\n+/g, ' / ').slice(0, 300));
  console.log('stop markers:', await page.evaluate(() => document.querySelectorAll('.mk-stop').length));
  await shot('5-navprev');
  // unfav -> chips gone, filter reset
  await page.keyboard.press('Escape'); await page.waitForTimeout(300); await click('[data-tab=tracks]'); await page.waitForTimeout(200);
  await click('[data-track=c]'); await page.waitForTimeout(400); await click('[data-tv=fav]'); await click('[data-tv=back]'); await page.waitForTimeout(400);
  console.log('after unfav chips:', await page.evaluate(() => !!document.querySelector('[data-trkfav]')), 'items:', await page.evaluate(() => document.querySelectorAll('#listBody [data-track]').length));
  console.log('errors', JSON.stringify(errs)); await b.close();
})();
