const BASE = process.env.BASE || 'http://127.0.0.1:8765', OUT = process.env.OUT || require('os').tmpdir();
const { chromium } = require('playwright');
const HS = process.env.CHROME_PATH || undefined;
(async () => { const b = await chromium.launch({...(HS ? {executablePath:HS} : {})});
  const ctx = await b.newContext({viewport:{width:390, height:844}, isMobile:true, hasTouch:true, serviceWorkers:'block'});
  await ctx.route(/arcgisonline|amazonaws|openfreemap|gstatic|firestore|osrm|valhalla|photon|open-meteo|nominatim|dwd|rainviewer|overpass/, r => r.abort());
  await ctx.addInitScript(() => { if(sessionStorage.getItem('i')) return; sessionStorage.setItem('i', 1);
    localStorage.setItem('meine-spots-prefs', JSON.stringify({labels:true, theme:'dark', onb:1}));
    localStorage.setItem('meine-spots-v1', JSON.stringify({cats:[{id:'c1"><img src=x onerror="window.__x=1">', name:'A', color:'#f00"><img src=x onerror="window.__x=2">', icon:'pin'}], spots:[{id:'s1', name:'Spot A', lat:50, lng:10, cat:'c1"><img src=x onerror="window.__x=1">', created:1}]}));
    const seg = []; for(let i = 0; i < 50; i++) seg.push([10 + i * .001, 50, i * 10]);
    localStorage.setItem('meine-spots-tracks', JSON.stringify([{id:'t1', name:'Fahrt 1', created:Date.now(), dist:3000, dur:500000, maxSpd:20, segs:[seg]}])); });
  const page = await ctx.newPage(); const errs = []; page.on('pageerror', e => errs.push(e.message));
  await page.goto(`${BASE}/index.html?noonb`); await page.waitForTimeout(2000);
  await page.evaluate(() => document.querySelector('#listBody .item')?.click()); await page.waitForTimeout(500);
  console.log('xss:', await page.evaluate(() => window.__x || 0), '| view detail:', await page.evaluate(() => !document.querySelector('#detailView').hidden));
  await page.goBack(); await page.waitForTimeout(500);
  console.log('after back: url', page.url().slice(-12), 'detail hidden:', await page.evaluate(() => document.querySelector('#detailView').hidden));
  console.log('ls tracks removed:', await page.evaluate(() => localStorage.getItem('meine-spots-tracks') === null));
  await page.reload(); await page.waitForTimeout(2000);
  await page.evaluate(() => document.querySelector('[data-tab=tracks]').click()); await page.waitForTimeout(400);
  console.log('tracks after reload:', await page.evaluate(() => document.querySelectorAll('#listBody [data-track]').length));
  console.log('errors', JSON.stringify(errs)); await b.close(); })();
