const BASE = process.env.BASE || 'http://127.0.0.1:8765', OUT = process.env.OUT || require('os').tmpdir();
const { chromium } = require('playwright');
const HS = process.env.CHROME_PATH || undefined;
(async () => { const b = await chromium.launch({...(HS ? {executablePath:HS} : {}), args:['--use-gl=swiftshader']});
  const ctx = await b.newContext({viewport:{width:390, height:844}, deviceScaleFactor:2, isMobile:true, hasTouch:true, serviceWorkers:'block'});
  await ctx.route(/arcgisonline|amazonaws|openfreemap|gstatic|firestore|osrm|valhalla|photon|open-meteo|nominatim|dwd|rainviewer|overpass/, r => r.abort());
  await ctx.addInitScript(() => { if(sessionStorage.getItem('i')) return; sessionStorage.setItem('i', 1);
    localStorage.setItem('meine-spots-prefs', JSON.stringify({labels:true, theme:'dark', onb:1}));
    const spots = []; for(let i = 0; i < 12; i++) spots.push({id:'s' + i, name:'Spot ' + String.fromCharCode(65 + i), lat:50 + i * .01, lng:10, cat:'c1', created:i});
    localStorage.setItem('meine-spots-v1', JSON.stringify({cats:[{id:'c1', name:'Aussicht mit sehr langem Kategorienamen', color:'#f80', icon:'pin'}], spots})); });
  const page = await ctx.newPage(); const errs = []; page.on('pageerror', e => errs.push(e.message));
  const click = s => page.evaluate(s => document.querySelector(s).click(), s);
  await page.goto(`${BASE}/index.html?noonb`); await page.waitForTimeout(2000);
  await click('#addBtn'); await page.waitForTimeout(700);
  console.log('mode btn bottom:', await page.evaluate(() => [...document.querySelectorAll('#modeView button')].map(x => Math.round(x.getBoundingClientRect().bottom)).join(',')), 'xhair:', await page.evaluate(() => getComputedStyle(document.querySelector('#xhair')).display));
  await page.screenshot({path:`${OUT}/fx-mode.png`});
  await click('#modeView [data-act=center]'); await page.waitForTimeout(700);
  console.log('edit focus:', await page.evaluate(() => document.activeElement.id), 'panel:', await page.evaluate(() => document.querySelector('#panel').style.transform));
  await page.fill('#f-name', 'Test'); await click('#editView [data-act=cancel]'); await page.waitForTimeout(200);
  console.log('armed:', await page.evaluate(() => document.querySelector('#editView [data-act=cancel]')?.textContent));
  await click('#editView [data-act=cancel]'); await page.waitForTimeout(500);
  console.log('view after cancel:', await page.evaluate(() => [...document.querySelectorAll('#panel .view')].filter(v => !v.hidden).map(v => v.id).join()));
  await click('#searchBtn'); await page.waitForTimeout(300); await page.fill('#q', 'spot'); await page.waitForTimeout(400);
  console.log('search items:', await page.evaluate(() => document.querySelectorAll('#listBody [data-id]').length), await page.evaluate(() => document.querySelector('[data-searchall]')?.innerText));
  await click('#listBody [data-id]'); await page.waitForTimeout(600); await page.screenshot({path:`${OUT}/fx-detail.png`});
  await click('#detailView [data-act=back]'); await page.waitForTimeout(600);
  console.log('back in search:', await page.evaluate(() => document.querySelector('#q').value));
  console.log('errors', JSON.stringify(errs)); await b.close(); })();
